baseURL = "https://royu.netlify.com/"
languageCode = "en-us"
title = "Robert's blog"
theme = "hyde"

disqusShortname = "royu-netlify-com"

[params]
    layoutReverse = true
    themeColor = "theme-base-08"
    favicon = "./favicon.ico"
    description = "Just some thoughts on computers."

